import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, FileText } from "lucide-react";
import { getServerLanguage } from "@/lib/i18n/server";

export function generateMetadata(): Metadata {
  const isRo = getServerLanguage() === "ro";
  return {
    title: isRo
      ? "PDF-uri generate cu AI — Knowledge Hub NutriAID"
      : "AI-Generated PDFs — NutriAID Knowledge Hub",
    description: isRo
      ? "Rapoartele PDF generate automat de NutriAID: ce conțin, cum le obții, cum le partajezi cu medicul sau nutriționistul tău."
      : "NutriAID's automatically generated PDF reports: what they contain, how to get them, and how to share them with your doctor or nutritionist.",
    alternates: { canonical: "/knowledge-hub/pdf-uri-generate", languages: { ro: "/knowledge-hub/pdf-uri-generate", en: "/knowledge-hub/pdf-uri-generate", "x-default": "/knowledge-hub/pdf-uri-generate" } },
    openGraph: {
      title: isRo ? "PDF-uri generate cu AI — NutriAID" : "AI-Generated PDFs — NutriAID",
      description: isRo
        ? "Rapoartele tale personalizate, generate automat de AI, gata de partajat cu specialiști medicali."
        : "Your personalized reports, automatically generated by AI, ready to share with medical specialists.",
      url: "/knowledge-hub/pdf-uri-generate",
      locale: isRo ? "ro_RO" : "en_US",
    },
  };
}

export default function PdfUriGeneratePage() {
  const isRo = getServerLanguage() === "ro";

  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: isRo ? "PDF-uri generate cu AI — NutriAID" : "AI-Generated PDFs — NutriAID",
    description: isRo
      ? "NutriAID generează rapoarte PDF personalizate cu analiza completă a intoleranțelor identificate de AI."
      : "NutriAID generates personalized PDF reports with complete AI-identified intolerance analysis.",
    author: { "@type": "Organization", name: "NutriAID Intolerances" },
    publisher: { "@type": "Organization", name: "NutriAID Intolerances" },
    url: "/knowledge-hub/pdf-uri-generate",
    inLanguage: isRo ? "ro-RO" : "en-US",
  };

  const pdfContents = isRo
    ? [
        { title: "Rezumatul perioadei analizate", body: "Numărul de mese înregistrate, simptome raportate și corelații detectate." },
        { title: "Lista alimentelor suspecte", body: "Alimentele cu probabilitate ridicată de a fi declanșatori, cu nivelul de certitudine al corelației." },
        { title: "Lista alimentelor sigure", body: "Alimentele consumate fără corelații cu simptomele, confirmate ca sigure pentru corpul tău." },
        { title: "Combinații problematice identificate", body: "Perechi sau grupuri de alimente care împreună declanșează simptome, chiar dacă singure nu sunt problematice." },
        { title: "Evoluția simptomelor", body: "Grafice și date despre cum s-au schimbat simptomele tale pe parcursul perioadei." },
        { title: "Recomandări personalizate", body: "Sfaturi adaptate corpului tău, bazate pe analiza completă a datelor acumulate." },
      ]
    : [
        { title: "Summary of analyzed period", body: "Number of logged meals, reported symptoms, and detected correlations." },
        { title: "Suspected foods list", body: "Foods with high probability of being triggers, with the correlation confidence level." },
        { title: "Safe foods list", body: "Foods consumed without symptom correlations, confirmed safe for your body." },
        { title: "Identified problematic combinations", body: "Pairs or groups of foods that together trigger symptoms, even if individually not problematic." },
        { title: "Symptom evolution", body: "Charts and data about how your symptoms changed over the period." },
        { title: "Personalized recommendations", body: "Advice adapted to your body, based on the complete analysis of accumulated data." },
      ];

  const useCases = isRo
    ? [
        "Partajează raportul cu medicul tău de familie sau gastroenterolog",
        "Prezintă-l nutriționistului pentru a rafina planul alimentar",
        "Păstrează-l ca jurnal personal de sănătate",
        "Urmărește evoluția în timp comparând rapoarte din perioade diferite",
        "Documentează progresul pentru a înțelege ce modificări alimentare au funcționat",
      ]
    : [
        "Share the report with your general practitioner or gastroenterologist",
        "Present it to a nutritionist to refine the food plan",
        "Keep it as a personal health journal",
        "Track evolution over time by comparing reports from different periods",
        "Document progress to understand which dietary changes worked",
      ];

  const faqItems = isRo
    ? [
        { q: "Cum generez un raport PDF in NutriAID?", a: "Din sectiunea Dashboard → Rapoarte, selectezi perioada dorita si apesi 'Genereaza raport'. Raportul este creat automat de AI pe baza datelor acumulate in perioada selectata." },
        { q: "Cat de des pot genera rapoarte PDF?", a: "Poti genera rapoarte oricand, pentru orice perioada dorita. Nu exista restrictii de frecventa — generezi un raport nou cand doresti date actualizate." },
        { q: "Pot partaja raportul PDF cu medicul meu?", a: "Da. Rapoartele sunt in format PDF standard, usor de trimis prin email sau de tiparit pentru o consultatie medicala, gastroenterologica sau nutritionala." },
        { q: "Raportul PDF contine diagnostice medicale?", a: "Nu. Rapoartele contin date, corelatii si recomandari bazate pe analiza AI, nu diagnostice medicale. Sunt documente informative bazate pe datele tale personale, nu documente medicale." },
        { q: "Rapoartele PDF se actualizeaza automat cu date noi?", a: "Nu. Fiecare raport este un snapshot al datelor din perioada selectata. Generezi un raport nou cand doresti o analiza actualizata cu datele recente." },
      ]
    : [
        { q: "How do I generate a PDF report in NutriAID?", a: "From the Dashboard → Reports section, select the desired period and click 'Generate report'. The report is automatically created by AI based on the data accumulated in the selected period." },
        { q: "How often can I generate PDF reports?", a: "You can generate reports at any time, for any desired period. There are no frequency restrictions — generate a new report whenever you want updated data." },
        { q: "Can I share the PDF report with my doctor?", a: "Yes. Reports are in standard PDF format, easy to send by email or print for a medical, gastroenterological, or nutritional consultation." },
        { q: "Does the PDF report contain medical diagnoses?", a: "No. Reports contain data, correlations, and AI-based recommendations, not medical diagnoses. They are informative documents based on your personal data, not medical documents." },
        { q: "Do PDF reports automatically update with new data?", a: "No. Each report is a snapshot of data from the selected period. You generate a new report when you want an analysis updated with recent data." },
      ];

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqItems.map((item) => ({
      "@type": "Question",
      name: item.q,
      acceptedAnswer: { "@type": "Answer", text: item.a },
    })),
  };

  return (
    <div className="pb-20 bg-slate-50 dark:bg-slate-950">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      <section className="relative overflow-hidden border-y border-emerald-100 dark:border-emerald-900/40 bg-gradient-to-b from-emerald-100 via-white to-slate-50 dark:from-emerald-950/30 dark:via-slate-950 dark:to-slate-950">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute -top-16 right-0 h-64 w-64 rounded-full bg-emerald-300/30 blur-3xl" />
          <div className="absolute -bottom-20 left-0 h-72 w-72 rounded-full bg-cyan-300/20 blur-3xl" />
        </div>
        <div className="relative mx-auto w-full max-w-4xl px-4 py-20 sm:px-6 lg:px-8 lg:py-24">
          <Link href="/knowledge-hub" className="inline-flex items-center gap-2 rounded-full bg-emerald-600/10 text-emerald-700 dark:text-emerald-300 px-4 py-1.5 text-sm font-semibold mb-6 hover:bg-emerald-600/20 transition">
            <BookOpen className="h-4 w-4" />
            Knowledge Hub
          </Link>
          <h1 className="text-4xl sm:text-5xl font-extrabold leading-tight text-slate-900 dark:text-white">
            {isRo ? "PDF-uri generate cu AI" : "AI-Generated PDFs"}
          </h1>
          <p className="mt-5 text-xl text-slate-700 dark:text-slate-300 max-w-3xl">
            {isRo
              ? "NutriAID generează automat rapoarte PDF personalizate cu analiza completă a intoleranțelor tale. Poți descărca, partaja sau folosi aceste rapoarte oricând."
              : "NutriAID automatically generates personalized PDF reports with your complete intolerance analysis. You can download, share, or use these reports at any time."}
          </p>
        </div>
      </section>

      <article className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-14 space-y-14">

        <section>
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 dark:text-white mb-6">
            {isRo ? "Ce conțin rapoartele PDF?" : "What do PDF reports contain?"}
          </h2>
          <ul className="space-y-4 list-none p-0">
            {pdfContents.map((item) => (
              <li key={item.title} className="flex items-start gap-4 rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-5">
                <FileText className="h-5 w-5 flex-none mt-0.5 text-emerald-600 dark:text-emerald-400" />
                <div>
                  <p className="font-semibold text-slate-900 dark:text-white mb-1">{item.title}</p>
                  <p className="text-slate-600 dark:text-slate-400 text-sm">{item.body}</p>
                </div>
              </li>
            ))}
          </ul>
        </section>

        <section>
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 dark:text-white mb-5">
            {isRo ? "Cum poți folosi rapoartele PDF?" : "How can you use the PDF reports?"}
          </h2>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none p-0">
            {useCases.map((item) => (
              <li key={item} className="flex items-start gap-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 px-4 py-3 text-slate-700 dark:text-slate-200">
                <CheckCircle2 className="h-4 w-4 mt-0.5 flex-none text-emerald-500 dark:text-emerald-400" />
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </section>

        <section className="rounded-2xl border border-cyan-200 dark:border-cyan-800 bg-cyan-50 dark:bg-cyan-950/20 p-6">
          <h2 className="text-xl font-bold text-slate-900 dark:text-cyan-100 mb-3">
            {isRo ? "Rapoartele sunt disponibile din dashboard" : "Reports are available from the dashboard"}
          </h2>
          <p className="text-slate-700 dark:text-slate-300">
            {isRo
              ? "Din secțiunea Dashboard → Rapoarte poți genera și descărca rapoartele PDF pentru orice perioadă dorită. Rapoartele sunt generate automat de AI pe baza datelor tale actuale."
              : "From the Dashboard → Reports section you can generate and download PDF reports for any desired period. Reports are automatically generated by AI based on your current data."}
          </p>
        </section>

        {/* Definitie */}
        <section>
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 dark:text-white mb-5">
            {isRo ? "Ce sunt rapoartele PDF generate cu AI?" : "What are AI-generated PDF reports?"}
          </h2>
          <p className="text-lg text-slate-700 dark:text-slate-300">
            {isRo
              ? "Rapoartele PDF generate cu AI sunt documente personalizate create automat de NutriAID pe baza istoricului tău de mese și simptome. Conțin analiza completă AI a perioadei selectate: corelații, alimente suspecte, alimente sigure și evoluția simptomelor — într-un format ușor de partajat cu un specialist medical."
              : "AI-generated PDF reports are personalized documents automatically created by NutriAID based on your meal and symptom history. They contain the complete AI analysis of the selected period: correlations, suspected foods, safe foods, and symptom evolution — in a format easy to share with a medical specialist."}
          </p>
        </section>

        {/* Importanta */}
        <section>
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 dark:text-white mb-5">
            {isRo ? "De ce sunt importante rapoartele PDF?" : "Why are PDF reports important?"}
          </h2>
          <p className="text-lg text-slate-700 dark:text-slate-300">
            {isRo
              ? "Rapoartele PDF transformă datele brute din jurnal în informații structurate și ușor de citit. Un medic sau nutriționist poate înțelege în câteva minute ce ai experimentat pe parcursul săptămânilor sau lunilor de înregistrare — economisind timp prețios la consultație și oferind context pentru recomandări mai precise."
              : "PDF reports transform raw journal data into structured, easy-to-read information. A doctor or nutritionist can understand in minutes what you experienced over weeks or months of logging — saving valuable consultation time and providing context for more precise recommendations."}
          </p>
        </section>

        {/* Pasi concreti */}
        <section>
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 dark:text-white mb-6">
            {isRo ? "Cum generezi un raport PDF pas cu pas?" : "How to generate a PDF report step by step?"}
          </h2>
          <ol className="space-y-3 list-none p-0">
            {(isRo
              ? [
                  { n: "1", t: "Accesezi Dashboard-ul", b: "Intri în contul tău NutriAID și navighezi la secțiunea Dashboard." },
                  { n: "2", t: "Deschizi secțiunea Rapoarte", b: "Găsești secțiunea dedicată rapoartelor în meniul principal al dashboard-ului." },
                  { n: "3", t: "Selectezi perioada", b: "Alegi intervalul de timp pentru care dorești analiza: ultima săptămână, ultima lună sau un interval personalizat." },
                  { n: "4", t: "Generezi raportul", b: "Apeși butonul 'Generează raport'. AI-ul procesează datele și creează PDF-ul automat." },
                  { n: "5", t: "Descarci și partajezi", b: "Descărci raportul PDF și îl trimiți medicului, nutriționistului sau îl păstrezi ca jurnal personal." },
                ]
              : [
                  { n: "1", t: "Access the Dashboard", b: "Log into your NutriAID account and navigate to the Dashboard section." },
                  { n: "2", t: "Open the Reports section", b: "Find the dedicated reports section in the main dashboard menu." },
                  { n: "3", t: "Select the period", b: "Choose the time interval for which you want the analysis: last week, last month, or a custom interval." },
                  { n: "4", t: "Generate the report", b: "Click the 'Generate report' button. The AI processes the data and creates the PDF automatically." },
                  { n: "5", t: "Download and share", b: "Download the PDF report and send it to your doctor, nutritionist, or keep it as a personal health journal." },
                ]
            ).map((step) => (
              <li key={step.n} className="flex items-start gap-4 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 px-4 py-3">
                <span className="inline-flex h-7 w-7 items-center justify-center rounded-md bg-emerald-600 text-white text-xs font-bold flex-none">{step.n}</span>
                <div>
                  <p className="font-semibold text-slate-900 dark:text-white">{step.t}</p>
                  <p className="text-slate-600 dark:text-slate-400 text-sm">{step.b}</p>
                </div>
              </li>
            ))}
          </ol>
        </section>

        {/* Exemplu */}
        <section className="rounded-2xl border border-emerald-200 dark:border-emerald-800 bg-emerald-50 dark:bg-emerald-950/20 p-6">
          <h2 className="text-xl font-bold text-emerald-800 dark:text-emerald-200 mb-3">
            {isRo ? "Exemplu concret de raport PDF" : "Concrete PDF report example"}
          </h2>
          <p className="text-slate-700 dark:text-slate-300">
            {isRo
              ? "Elena generează raportul pentru ultima lună: 127 mese înregistrate, 23 de simptome raportate, 3 alimente suspecte identificate (grâu, lapte de vacă, roșii cherry), 47 de alimente sigure confirmate, evoluție simptome: -60% față de prima săptămână. Trimite raportul gastroenterologului înainte de consultație. Medicul are acum context complet în locul unui rezumat verbal de 5 minute."
              : "Elena generates the report for the last month: 127 meals logged, 23 symptoms reported, 3 suspected foods identified (wheat, cow's milk, cherry tomatoes), 47 safe foods confirmed, symptom evolution: -60% compared to the first week. She sends the report to her gastroenterologist before the consultation. The doctor now has complete context instead of a 5-minute verbal summary."}
          </p>
        </section>

        {/* Tabel comparativ */}
        <section>
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 dark:text-white mb-6">
            {isRo ? "Raport NutriAID vs. alte metode de documentare" : "NutriAID report vs. other documentation methods"}
          </h2>
          <div className="overflow-x-auto rounded-2xl border border-slate-200 dark:border-slate-700">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-emerald-600 text-white text-left">
                  <th className="px-4 py-3 font-semibold">{isRo ? "Criteriu" : "Criterion"}</th>
                  <th className="px-4 py-3 font-semibold">{isRo ? "Raport PDF NutriAID" : "NutriAID PDF Report"}</th>
                  <th className="px-4 py-3 font-semibold">{isRo ? "Jurnal manual" : "Manual journal"}</th>
                  <th className="px-4 py-3 font-semibold">{isRo ? "Foaie observații" : "Observation sheet"}</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-700">
                {(isRo
                  ? [
                      ["Generare automată", "✅ Da", "❌ Nu", "❌ Nu"],
                      ["Analiză AI inclusă", "✅ Da", "❌ Nu", "❌ Nu"],
                      ["Corelații calculate", "✅ Da", "❌ Nu", "❌ Nu"],
                      ["Format partajabil", "PDF standard", "Variabil", "Da"],
                      ["Timp de creare", "Secunde", "Ore", "Zeci de minute"],
                      ["Actualizare cu date noi", "Regenerezi oricând", "Manual", "Manual"],
                    ]
                  : [
                      ["Automatic generation", "✅ Yes", "❌ No", "❌ No"],
                      ["AI analysis included", "✅ Yes", "❌ No", "❌ No"],
                      ["Correlations calculated", "✅ Yes", "❌ No", "❌ No"],
                      ["Shareable format", "Standard PDF", "Variable", "Yes"],
                      ["Creation time", "Seconds", "Hours", "Tens of minutes"],
                      ["Update with new data", "Regenerate anytime", "Manual", "Manual"],
                    ]
                ).map((row) => (
                  <tr key={row[0]} className="bg-white dark:bg-slate-900 even:bg-slate-50 even:dark:bg-slate-800/40">
                    <td className="px-4 py-3 font-medium text-slate-900 dark:text-white">{row[0]}</td>
                    <td className="px-4 py-3 text-emerald-700 dark:text-emerald-300 font-medium">{row[1]}</td>
                    <td className="px-4 py-3 text-slate-600 dark:text-slate-400">{row[2]}</td>
                    <td className="px-4 py-3 text-slate-600 dark:text-slate-400">{row[3]}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* FAQ */}
        <section>
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 dark:text-white mb-6">
            {isRo ? "Întrebări frecvente" : "Frequently asked questions"}
          </h2>
          <dl className="space-y-3">
            {faqItems.map((item) => (
              <div key={item.q} className="rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-5">
                <dt className="font-semibold text-slate-900 dark:text-white mb-2">{item.q}</dt>
                <dd className="text-slate-600 dark:text-slate-400 text-sm m-0">{item.a}</dd>
              </div>
            ))}
          </dl>
        </section>

        {/* Rezumat */}
        <section className="rounded-2xl border border-emerald-200 dark:border-emerald-800 bg-emerald-50 dark:bg-emerald-950/20 p-6">
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">
            {isRo ? "Rezumat" : "Summary"}
          </h2>
          <ul className="space-y-2 list-none p-0">
            {(isRo
              ? [
                  "Rapoartele PDF sunt generate automat de AI pe baza datelor tale de mese și simptome",
                  "Conțin: rezumat perioadă, alimente suspecte/sigure, combinații problematice, evoluție simptome",
                  "Se generează din Dashboard → Rapoarte, pentru orice perioadă dorită",
                  "Utile pentru partajarea cu medicul, gastroenterologul sau nutriționistul",
                  "Fiecare raport este un snapshot — generezi unul nou pentru date actualizate",
                  "Nu conțin diagnostice medicale — sunt documente informative bazate pe datele tale",
                ]
              : [
                  "PDF reports are automatically generated by AI based on your meal and symptom data",
                  "They contain: period summary, suspected/safe foods, problematic combinations, symptom evolution",
                  "Generated from Dashboard → Reports, for any desired period",
                  "Useful for sharing with your doctor, gastroenterologist, or nutritionist",
                  "Each report is a snapshot — generate a new one for updated data",
                  "They do not contain medical diagnoses — they are informative documents based on your data",
                ]
            ).map((point) => (
              <li key={point} className="flex items-start gap-2 text-slate-700 dark:text-slate-300">
                <CheckCircle2 className="h-4 w-4 mt-0.5 flex-none text-emerald-500 dark:text-emerald-400" />
                <span>{point}</span>
              </li>
            ))}
          </ul>
        </section>

        <section className="rounded-3xl bg-gradient-to-br from-emerald-700 to-cyan-700 p-8 text-center">
          <h2 className="text-2xl font-extrabold text-white mb-3">
            {isRo ? "Generează primul tău raport personalizat." : "Generate your first personalized report."}
          </h2>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-3 mt-6">
            <Link href="/auth/register" className="inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3 text-sm font-semibold text-emerald-700 hover:bg-emerald-50 transition">
              {isRo ? "Începe analiza" : "Start analysis"}
              <ArrowRight className="h-4 w-4" />
            </Link>
            <Link href="/knowledge-hub" className="inline-flex items-center rounded-xl border border-white/35 bg-white/10 px-6 py-3 text-sm font-semibold text-white hover:bg-white/20 transition">
              {isRo ? "Înapoi la Knowledge Hub" : "Back to Knowledge Hub"}
            </Link>
          </div>
        </section>
      </article>
    </div>
  );
}
