"use client";

import React, { useState, useEffect, useCallback } from "react";
import {
  Search,
  Filter,
  Clock,
  Flame,
  ChefHat,
  UtensilsCrossed,
  X,
  Loader2,
  BookOpen,
  FileDown,
  Lock,
} from "lucide-react";
import { useLanguage } from "@/components/LanguageProvider";
import { useRouter } from "next/navigation";
import { getSessionUser } from "@/lib/api/auth";
import RecipeModal from "@/components/RecipeModal";
import type { RecipeLocalized, RecipeCategory, RecipeDifficulty } from "@/types/recipes";

const copy = {
  ro: {
    title: "Rețete",
    subtitle: "Descoperă rețete sănătoase, personalizate pentru tine",
    searchPlaceholder: "Caută rețete...",
    filterCategory: "Categorie",
    filterDifficulty: "Dificultate",
    filterMaxTime: "Timp max (min)",
    allCategories: "Toate",
    allDifficulties: "Toate",
    categories: {
      breakfast: "Mic dejun",
      lunch: "Prânz",
      dinner: "Cină",
      snack: "Gustare",
    },
    difficulty: {
      easy: "Ușor",
      medium: "Mediu",
      hard: "Dificil",
    },
    minutes: "min",
    calories: "cal",
    noResults: "Nicio rețetă găsită.",
    noResultsDesc: "Încearcă să modifici filtrele sau adaugă rețete prin panoul de admin.",
    loading: "Se încarcă rețetele...",
    cook: "Gătește",
    loadMore: "Încarcă mai multe",
    empty: "Nu există rețete disponibile încă.",
    emptyDesc: "Rețetele sunt generate progresiv de sistemul AI.",
  },
  en: {
    title: "Recipes",
    subtitle: "Discover healthy recipes, personalized for you",
    searchPlaceholder: "Search recipes...",
    filterCategory: "Category",
    filterDifficulty: "Difficulty",
    filterMaxTime: "Max time (min)",
    allCategories: "All",
    allDifficulties: "All",
    categories: {
      breakfast: "Breakfast",
      lunch: "Lunch",
      dinner: "Dinner",
      snack: "Snack",
    },
    difficulty: {
      easy: "Easy",
      medium: "Medium",
      hard: "Hard",
    },
    minutes: "min",
    calories: "cal",
    noResults: "No recipes found.",
    noResultsDesc: "Try adjusting the filters or add recipes via the admin panel.",
    loading: "Loading recipes...",
    cook: "Cook",
    loadMore: "Load more",
    empty: "No recipes available yet.",
    emptyDesc: "Recipes are progressively generated by the AI system.",
  },
};

const CATEGORIES: RecipeCategory[] = ["breakfast", "lunch", "dinner", "snack"];
const DIFFICULTIES: RecipeDifficulty[] = ["easy", "medium", "hard"];
const PAGE_SIZE = 20;

const difficultyColors: Record<RecipeDifficulty, string> = {
  easy: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400",
  medium: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400",
  hard: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400",
};

const categoryColors: Record<RecipeCategory, string> = {
  breakfast: "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400",
  lunch: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400",
  dinner: "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400",
  snack: "bg-pink-100 text-pink-700 dark:bg-pink-900/30 dark:text-pink-400",
};

function RecipeCard({
  recipe,
  lang,
  t,
  onOpen,
}: {
  recipe: RecipeLocalized;
  lang: "ro" | "en";
  t: typeof copy["ro"];
  onOpen: () => void;
}) {
  return (
    <div
      className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 overflow-hidden hover:shadow-md transition-shadow cursor-pointer group"
      onClick={onOpen}
    >
      {/* Placeholder image area */}
      <div className="h-32 bg-gradient-to-br from-emerald-50 to-teal-100 dark:from-emerald-900/20 dark:to-teal-900/20 flex items-center justify-center">
        {recipe.imageUrl ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={recipe.imageUrl} alt={recipe.title} className="w-full h-full object-cover" />
        ) : (
          <UtensilsCrossed className="w-10 h-10 text-emerald-300 dark:text-emerald-700 group-hover:scale-110 transition-transform" />
        )}
      </div>

      <div className="p-4">
        {/* Badges */}
        <div className="flex items-center gap-1.5 flex-wrap mb-2">
          <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${categoryColors[recipe.category]}`}>
            {t.categories[recipe.category]}
          </span>
          <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${difficultyColors[recipe.difficulty]}`}>
            {t.difficulty[recipe.difficulty]}
          </span>
        </div>

        <h3 className="text-sm font-semibold text-slate-900 dark:text-white line-clamp-2 mb-2 leading-snug">
          {recipe.title}
        </h3>

        <div className="flex items-center gap-3 text-xs text-slate-500 dark:text-slate-400">
          <span className="flex items-center gap-1">
            <Clock className="w-3 h-3" />
            {recipe.prepTimeMinutes} {t.minutes}
          </span>
          {recipe.calories && (
            <span className="flex items-center gap-1">
              <Flame className="w-3 h-3 text-orange-400" />
              {recipe.calories} {t.calories}
            </span>
          )}
          {recipe.cuisine && (
            <span className="truncate">{recipe.cuisine}</span>
          )}
        </div>

        <div className="mt-3 flex gap-2">
          <button
            type="button"
            onClick={(e) => { e.stopPropagation(); onOpen(); }}
            className="flex-1 flex items-center justify-center gap-1.5 px-3 py-2 bg-emerald-50 dark:bg-emerald-900/20 hover:bg-emerald-100 dark:hover:bg-emerald-900/40 text-emerald-700 dark:text-emerald-300 text-xs font-semibold rounded-xl transition-colors"
          >
            <ChefHat className="w-3.5 h-3.5" />
            {t.cook}
          </button>
          <a
            href={`/api/recipes/${recipe.id}/pdf?lang=${lang}`}
            download
            onClick={(e) => e.stopPropagation()}
            className="flex items-center justify-center gap-1 px-3 py-2 bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600 text-slate-600 dark:text-slate-300 text-xs font-semibold rounded-xl transition-colors"
            title={lang === "ro" ? "Descarcă PDF" : "Download PDF"}
          >
            <FileDown className="w-3.5 h-3.5" />
          </a>
        </div>
      </div>
    </div>
  );
}

export default function RecipesPage() {
  const { lang } = useLanguage();
  const t = copy[lang as "ro" | "en"] ?? copy.en;
  const effectiveLang = (lang === "ro" ? "ro" : "en") as "ro" | "en";
  const router = useRouter();
  const [accessDenied, setAccessDenied] = useState(false);

  const [recipes, setRecipes] = useState<RecipeLocalized[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadingMore, setLoadingMore] = useState(false);
  const [hasMore, setHasMore] = useState(true);
  const [offset, setOffset] = useState(0);
  const [selectedRecipe, setSelectedRecipe] = useState<RecipeLocalized | null>(null);

  const [query, setQuery] = useState("");
  const [category, setCategory] = useState<RecipeCategory | "">("");
  const [difficulty, setDifficulty] = useState<RecipeDifficulty | "">("");
  const [maxTime, setMaxTime] = useState<number | "">("");
  const [showFilters, setShowFilters] = useState(false);

  const buildUrl = useCallback(
    (currentOffset: number) => {
      const params = new URLSearchParams({ lang: effectiveLang, limit: String(PAGE_SIZE), offset: String(currentOffset) });
      if (query) params.set("q", query);
      if (category) params.set("category", category);
      if (difficulty) params.set("difficulty", difficulty);
      if (maxTime) params.set("maxPrepTime", String(maxTime));
      return `/api/recipes?${params.toString()}`;
    },
    [effectiveLang, query, category, difficulty, maxTime]
  );

  const fetchRecipes = useCallback(async () => {
    setLoading(true);
    setOffset(0);
    try {
      const res = await fetch(buildUrl(0));
      const data = await res.json() as { recipes: RecipeLocalized[]; count: number };
      setRecipes(data.recipes ?? []);
      setHasMore((data.recipes ?? []).length === PAGE_SIZE);
    } catch {
      setRecipes([]);
    } finally {
      setLoading(false);
    }
  }, [buildUrl]);

  const fetchMore = async () => {
    const nextOffset = offset + PAGE_SIZE;
    setLoadingMore(true);
    try {
      const res = await fetch(buildUrl(nextOffset));
      const data = await res.json() as { recipes: RecipeLocalized[]; count: number };
      setRecipes((prev) => [...prev, ...(data.recipes ?? [])]);
      setHasMore((data.recipes ?? []).length === PAGE_SIZE);
      setOffset(nextOffset);
    } catch {
      // silent
    } finally {
      setLoadingMore(false);
    }
  };

  useEffect(() => {
    getSessionUser().then((user) => {
      if (!user) { router.push("/dashboard"); return; }
      const allowed =
        user.role === "superadmin" ||
        user.plan === "pro_plus" ||
        user.earlyAdopter ||
        !user.plan;
      if (!allowed) setAccessDenied(true);
    }).catch(() => router.push("/dashboard"));
  }, [router]);

  // Fetch on mount and when lang changes
  useEffect(() => {
    fetchRecipes();
  }, [fetchRecipes]);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    fetchRecipes();
  };

  const clearFilters = () => {
    setQuery("");
    setCategory("");
    setDifficulty("");
    setMaxTime("");
  };

  const hasActiveFilters = !!query || !!category || !!difficulty || !!maxTime;

  if (accessDenied) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] text-center px-4">
        <div className="w-16 h-16 bg-purple-100 dark:bg-purple-900/30 rounded-2xl flex items-center justify-center mb-4">
          <Lock className="w-8 h-8 text-purple-500 dark:text-purple-400" />
        </div>
        <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-2">
          {lang === "ro" ? "Acces restricționat" : "Access restricted"}
        </h2>
        <p className="text-slate-500 dark:text-slate-400 max-w-sm mb-6">
          {lang === "ro"
            ? "Modulul de rețete este disponibil pentru planurile Free și Pro+. Fă upgrade pentru a debloca această funcționalitate."
            : "The recipes module is available on Free and Pro+ plans. Upgrade your plan to unlock this feature."}
        </p>
        <a
          href="/pricing"
          className="px-5 py-2.5 bg-purple-600 hover:bg-purple-700 text-white text-sm font-semibold rounded-xl transition-colors"
        >
          {lang === "ro" ? "Vezi planurile" : "View plans"}
        </a>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 bg-emerald-100 dark:bg-emerald-900/30 rounded-xl flex items-center justify-center">
          <BookOpen className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
        </div>
        <div>
          <h1 className="text-xl font-bold text-slate-900 dark:text-white">{t.title}</h1>
          <p className="text-sm text-slate-500 dark:text-slate-400">{t.subtitle}</p>
        </div>
      </div>

      {/* Search & Filters */}
      <form onSubmit={handleSearch} className="space-y-3">
        <div className="flex gap-2">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder={t.searchPlaceholder}
              className="w-full pl-9 pr-4 py-2.5 rounded-xl border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-800 text-slate-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
            />
          </div>
          <button
            type="button"
            onClick={() => setShowFilters((v) => !v)}
            className={`px-3 py-2.5 rounded-xl border text-sm font-medium transition-colors flex items-center gap-1.5 ${
              showFilters || hasActiveFilters
                ? "border-emerald-500 bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-300"
                : "border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-300"
            }`}
          >
            <Filter className="w-4 h-4" />
          </button>
          <button
            type="submit"
            className="px-4 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white text-sm font-semibold rounded-xl transition-colors"
          >
            <Search className="w-4 h-4" />
          </button>
        </div>

        {showFilters && (
          <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 p-4 space-y-3">
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
              {/* Category */}
              <div>
                <label className="block text-xs font-medium text-slate-600 dark:text-slate-400 mb-1">
                  {t.filterCategory}
                </label>
                <select
                  value={category}
                  onChange={(e) => setCategory(e.target.value as RecipeCategory | "")}
                  className="w-full px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-700 text-slate-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
                >
                  <option value="">{t.allCategories}</option>
                  {CATEGORIES.map((c) => (
                    <option key={c} value={c}>{t.categories[c]}</option>
                  ))}
                </select>
              </div>

              {/* Difficulty */}
              <div>
                <label className="block text-xs font-medium text-slate-600 dark:text-slate-400 mb-1">
                  {t.filterDifficulty}
                </label>
                <select
                  value={difficulty}
                  onChange={(e) => setDifficulty(e.target.value as RecipeDifficulty | "")}
                  className="w-full px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-700 text-slate-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
                >
                  <option value="">{t.allDifficulties}</option>
                  {DIFFICULTIES.map((d) => (
                    <option key={d} value={d}>{t.difficulty[d]}</option>
                  ))}
                </select>
              </div>

              {/* Max prep time */}
              <div>
                <label className="block text-xs font-medium text-slate-600 dark:text-slate-400 mb-1">
                  {t.filterMaxTime}
                </label>
                <input
                  type="number"
                  value={maxTime}
                  onChange={(e) => setMaxTime(e.target.value ? Number(e.target.value) : "")}
                  placeholder="60"
                  min={1}
                  max={240}
                  className="w-full px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-700 text-slate-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
                />
              </div>
            </div>

            {hasActiveFilters && (
              <button
                type="button"
                onClick={clearFilters}
                className="flex items-center gap-1.5 text-xs text-slate-500 dark:text-slate-400 hover:text-red-500 dark:hover:text-red-400 transition-colors"
              >
                <X className="w-3.5 h-3.5" />
                {effectiveLang === "ro" ? "Șterge filtrele" : "Clear filters"}
              </button>
            )}
          </div>
        )}
      </form>

      {/* Content */}
      {loading ? (
        <div className="flex flex-col items-center justify-center py-16 gap-3">
          <Loader2 className="w-8 h-8 text-emerald-500 animate-spin" />
          <p className="text-sm text-slate-500 dark:text-slate-400">{t.loading}</p>
        </div>
      ) : recipes.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-16 text-center">
          <div className="w-16 h-16 bg-slate-100 dark:bg-slate-800 rounded-2xl flex items-center justify-center mb-4">
            <UtensilsCrossed className="w-8 h-8 text-slate-400" />
          </div>
          <p className="text-slate-700 dark:text-slate-300 font-semibold mb-1">
            {hasActiveFilters ? t.noResults : t.empty}
          </p>
          <p className="text-sm text-slate-500 dark:text-slate-400 max-w-xs">
            {hasActiveFilters ? t.noResultsDesc : t.emptyDesc}
          </p>
        </div>
      ) : (
        <>
          <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4">
            {recipes.map((recipe) => (
              <RecipeCard
                key={recipe.id}
                recipe={recipe}
                lang={effectiveLang}
                t={t}
                onOpen={() => setSelectedRecipe(recipe)}
              />
            ))}
          </div>

          {hasMore && (
            <div className="flex justify-center pt-2">
              <button
                type="button"
                onClick={fetchMore}
                disabled={loadingMore}
                className="flex items-center gap-2 px-6 py-2.5 rounded-xl border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 text-sm font-medium hover:bg-slate-50 dark:hover:bg-slate-700 disabled:opacity-50 transition-colors"
              >
                {loadingMore ? <Loader2 className="w-4 h-4 animate-spin" /> : null}
                {t.loadMore}
              </button>
            </div>
          )}
        </>
      )}

      {/* Recipe Modal */}
      {selectedRecipe && (
        <RecipeModal
          recipe={selectedRecipe}
          lang={effectiveLang}
          onClose={() => setSelectedRecipe(null)}
        />
      )}
    </div>
  );
}
